### ISSUE TITLE
Possible to run on file change/addition/deletion when using webpack watch?

### ISSUE THREAD

**Issue by praveenperera** [kevlened/copy-webpack-plugin#10]
When running webpack watch is it possible to have the files copied over automatically when a change happens? For example, if a new image is added to the folder automatically copy it over to the destination folder, or delete an image if it is deleted from the `from` folder or change the file name if it changes ect... Currently, you have to restart webpack --watch or run the build again for the changes to take into effect.

**Comment by kevlened** [comment]
This plugin already works with `webpack --watch` on both files and directories, it just won't show in the command line, because the assets created aren't chunks. I use webpack's file and directory tracking as shown below:

[Where I add files for webpack to track](https://github.com/kevlened/copy-webpack-plugin/blob/master/index.js#L95)
[Where I add directories for webpack to track](https://github.com/kevlened/copy-webpack-plugin/blob/master/index.js#L102)

**Comment by praveenperera** [comment]
Hey I tried adding a file into the directory while webpack --watch is running but it didn't automatically move it to the `to` directory.

**Comment by kevlened** [comment]
Weird. I'll try to repro. The plugin api for watching directories is being used properly:

[sokra](https://github.com/webpack/webpack-dev-server/issues/34#issuecomment-47420992)
[sample plugin](https://github.com/webpack/webpack/blob/9f440e30ecac00bfc27b91d372a969d3414d194c/lib/CachePlugin.js#L39)

**Comment by kevlened** [comment]
I'm unable to repro your issue. Files added to watched directories (whether absolute or relative) are updated in my build directory.

**Comment by kevlened** [comment]
Are the files you're adding in a nested directory in assets?

**Comment by kevlened** [comment]
Hmm, nevermind. Still can't repro

**Comment by praveenperera** [comment]
Hey thanks for your help, I do not have to much experience with webpack, I am using it as a build tool for a Elixir + Phoenix project. 

Here is my webpack config file: https://gist.github.com/praveenperera/61de643d282993cb82c7

I followed this tutorial to get it setup: http://matthewlehner.net/using-webpack-with-phoenix-and-elixir/

And in the tutorial they state `With this configuration, you are required to restart webpack when a file is added to this directory`, so they are having the same problem as well. 

I am tried this `webpack --watch` it builds it fine, but while run is watching the changes in the directory are not carried over. 

The from folder is the `./web/static/assets` and it has a favicon.ico, robots.txt and a images folder with a few image files.

Thanks again for the help, let me know if theres any other information that you need.

**Comment by kevlened** [comment]
Using [his own git repo](https://github.com/matthewlehner/phoenix-webpack-example), I'm not able to repro the issue:

1) Clone it
2) run `npm install`
3) comment out [a missing file in his webpack.config.js](https://github.com/matthewlehner/phoenix-webpack-example/blob/master/webpack.config.js#L48)
4) in the package.json, add `watch: "webpack --watch"` to his scripts
5) `npm run watch`
6) Add a file to `./web/static/assets` and watch it appear in `priv/static`

**Comment by praveenperera** [comment]
This is so weird, I tried the above and it still doesn't work maybe a webpack issue?

Webpack version: 1.12.12
Node: 5.5.0
NPM: 3.5.3

**Comment by kevlened** [comment]
I don't have webpack installed globally. `npm run` uses modules from the local node_modules.

Webpack: 1.12.12
Node: 4.2.6
NPM: 2.14.12

**Comment by praveenperera** [comment]
I'm pretty stumped, not sure what else to try. Thanks for your help though.

**Comment by kevlened** [comment]
Just tested it on:
Webpack version: 1.12.12
Node: 5.5.0
NPM: 3.5.3
OS: OSX 10.11.3

My guess is that it's because webpack is installed globally. I'll try that

**Comment by kevlened** [comment]
Nope, works then too. It's not copying at all? It won't show up in the terminal, but it should be copying the files.

**Comment by praveenperera** [comment]
Nope I've tried adding files, changing file names and deleting files. None of the changes shows up in the priv/static folder unless I restart webpack --watch

**Comment by kevlened** [comment]
Very weird. If you get it working, let me know what changed!

**Comment by praveenperera** [comment]
Will do,

I just tried it on a different computer that didn't even have node on it yet. I installed node, cloned the repo,  added webpack --watch to the package.json, ran npm run watch and still no luck. Copies all the files over when its first run but not while running.

**Comment by evilebottnawi** [comment]
@kevlened i have same error, but only if i copied file or files from directory placed in `node_modules` (in other places all works fine).
Example:
```js
const cwd = path.resolve(__dirname, '../../..');
const srcDir = path.join(cwd, 'src');
const buildDir = path.join(cwd, 'build');

new CopyWebpackPlugin([
            {
                from: path.join(cwd, 'node_modules/jquery/dist/jquery.js'),
                to: 'vendor/jquery/jquery.js'
            }
        ])
```
I am try to debug and find what files pushed in `compilation.fileDependencies`, maybe related to `webpack`?

**Comment by evilebottnawi** [comment]
Do not just copy a work out when files are changed, but if I change a file and then change any entry, the changed file is copied as needed

**Comment by evilebottnawi** [comment]
@kevlened The problem was in the file manager for some reason he refused to write to that directory) sorry for taken away time :smile:

**Comment by carpogoryanin** [comment]
Don't work for me too.

**Comment by HauntedSmores** [comment]
Everything is working except if you delete a file, that file is not removed from the output directory. So addition and changes to a source file will trigger that addition or change to output but not deletion.

**Comment by Badalik** [comment]
I have the same problem
