### ISSUE TITLE
Flatten deep nested matches?

### ISSUE THREAD

**Issue by Milewski** [kevlened/copy-webpack-plugin#106]
is there anyway to flatten the copied files to a single folder?? for example

i might have a bunch of nested folders and grab only the files i want by using this glob ```assets/**/*.{jpg,png} ``` and i want to output them to ```dist``` however it keeps the folder structure... would it be possible to copy all deep nested matches to a single flattened folder... ??

**Comment by kevlened** [comment]
There's a command called `flatten` in the README that should work.
