### ISSUE TITLE
Error: Output filename not configured

### ISSUE THREAD

**Issue by niksmac** [kevlened/copy-webpack-plugin#108]
Here is my `webpack.config.js`

```
var CopyWebpackPlugin = require('copy-webpack-plugin');
var path = require('path');

module.exports = {
  plugins: [
    new CopyWebpackPlugin([
      {
        from: 'dist/**/*',
        to: 'src/renderer/styles'
      }
    ])
  ]
};

```

Returns nothing but `Output filename not configured.`

Running on Mac `10.12.2`

**Comment by QWp6t** [comment]
User error. Read the docs.

**Comment by kevlened** [comment]
This is an issue with your webpack configuration, not the CopyWebpackPlugin

http://stackoverflow.com/questions/34157313/output-filename-not-configured-error-in-webpack

**Comment by valeriob** [comment]
Hi, i have the same problem, probably i'm using this plugin wrong.
How did you solve it ?

**Comment by atav32** [comment]
I think the example in the Readme is confusing cause the module doesn't have an entry or output.
