### ISSUE TITLE
Add debug information printed in WebPack debug mode

### ISSUE THREAD

**Issue by FractalizeR** [kevlened/copy-webpack-plugin#11]
Currently plugin doesn't copy anything for me so I would like debugging mode to be available. I'm using the following config:

``` js
var CopyWebpackPlugin = require ( 'copy-webpack-plugin' );

module.exports = {
    debug: true,
    externals: { jquery: "jQuery" },

    entry: './res/js/entry.ts',
    output: {
        path: __dirname + "/web",
        filename: 'js/app.js'
    },
    module: {
        loaders: [
            // note that babel-loader is not required
            { test: /\.tsx?$/, loader: 'ts-loader' }
        ],
        plugins: [
            new CopyWebpackPlugin ( [
                    // {output}/file.txt
                    {
                        from: __dirname + '/node_modules/bootstrap/dist/bootstrap.min.js',
                        to: "js"
                    }
                ]
            )
        ]
    }
};
```

**Comment by kevlened** [comment]
If you have any info on how to add debugging information (warnings, errors, etc) on webpack plugins, I'll look into it

**Comment by FractalizeR** [comment]
I think [this](https://github.com/webpack/webpack/blob/5bfc68aacb2294ec7778c5e68fea71a80cea6dbe/lib/ModuleWarning.js) is how warnings are created in webpack:

**Comment by kevlened** [comment]
Debugging is a plugin option in v4.0.0. The plugin doesn't respect webpack's global debug option, because that feature is removed in webpack 2.
