### ISSUE TITLE
Throw error if source or target does not exist

### ISSUE THREAD

**Issue by FractalizeR** [kevlened/copy-webpack-plugin#12]
Plugin doesn't copy anything anywhere for me and I guess I made a mistake in paths. I guess this should be an error in the plugin when `from` or` to` is not recognized as a correct, accessible file or directory.

**Comment by kevlened** [comment]
Seems like a duplicate of #11

**Comment by FractalizeR** [comment]
I am not sure this is a duplicate. Debugging info is a one thing. But throwing an error if source or target folder does not exist - is another one.
