### ISSUE TITLE
Naming output files based on path

### ISSUE THREAD

**Issue by eejdoowad** [kevlened/copy-webpack-plugin#124]
I have the following files

```
config/A/default.json
config/B/default.json
config/C/default.json
```

I want to output them as

```
out/A.json
out/B.json
out/C.json
```

I haven't had any luck. The closest I've got

```
 {
    context: 'config',
    from: '**/default.json,
    to: 'out[path].json'
}

```
outputs

```
out/A/.json
out/B/.json
out/C/.json
```

Any ideas?

Also, is this project dead? No commits in 6 months.

**Comment by thw0rted** [comment]
I'm looking at [the interpolation docs](https://github.com/webpack/loader-utils#interpolatename) and I don't see any easy way to get the path without the trailing slash, unless `[folder]` does that. Maybe upvote #107 ?

**Comment by eejdoowad** [comment]
Thanks so much. [folder] is exactly what I needed.
