### ISSUE TITLE
Do not use fs to copy files; declare target files as assets to webpack

### ISSUE THREAD

**Issue by gajus** [kevlened/copy-webpack-plugin#13]
The current implementation is doing the heavy lifting of [creating directory structure and copying the files](https://github.com/kevlened/copy-webpack-plugin/blob/f02a9f9b34bde5250dcab9f9bbe39cccc41f4ab6/index.js#L89). A better approach would be to simply add the target files to the webpack assets collection (e.g. [`html-webpack-plugin`](https://github.com/ampedandwired/html-webpack-plugin/blob/v2.7.2/lib/compiler.js) `./lib/compiler.js` does just that). Leave it up to webpack to copy the assets.

With this setup, for those who want `copy-webpack-plugin` to work with `webpack-dev-server` you can use [`write-file-webpack-plugin`](https://github.com/gajus/write-file-webpack-plugin).

**Comment by gajus** [comment]
One of the downsides of the current setup is that all files are copied upon any file change. Using the above approach in combination with `write-file-webpack-plugin` would leverage file hashing to detect changes and only write when needed.

Another thing to consider is that at the moment, files declared in `copy-webpack-plugin` do not appear in [`stats.compilation.assets`](https://github.com/gajus/write-file-webpack-plugin/blob/59accf6c040f9f8f0aff0067b8e45b483c99c676/src/index.js#L110) making it hard to debug/ track `copy-webpack-plugin` changes.

**Comment by kevlened** [comment]
I only use `fs` to write files if the `to` destination is an absolute path; adding to [compilation.assets is the default](https://github.com/kevlened/copy-webpack-plugin/blob/master/index.js#L158). When you include files in compilation.assets, they're relative to the target build directory, but an absolute path may be outside the target build directory.

Also, absolute path files are copied on any file change. I [check to see if there are updates before writing files to compilation.assets](https://github.com/kevlened/copy-webpack-plugin/blob/master/index.js#L157). I can add a check for absolute paths too.

It sounds like you're using an absolute path to describe files that are in your target build directory. I'll change it so `fs` is only used iff the destination is absolute and outside the target build directory. That should fix your problem.

Files are usually included in `stats.compilation.assets` on the first build. However, when `webpack --watch` is used, files appear on the first build, but subsequent builds don't show the file changes, even though only changed files are copied. I'm not sure what's going on their, I'll open another issue to track it.

**Comment by gajus** [comment]
> I only use fs to write files if the to destination is an absolute path; adding to compilation.assets is the default. When you include files in compilation.assets, they're relative to the target build directory, but an absolute path may be outside the target build directory.

Can you not use a relative path that refers to a directory outside the build directory? Writing logic for resolving such path is pretty simple, assuming webpack allows it.

**Comment by kevlened** [comment]
Looks like webpack does support relative paths in compilation.assets. I'll merge a fix

**Comment by gajus** [comment]
:+1:

**Comment by gajus** [comment]
`stats.compilation.assets` asset path should be relative to `compiler.options.output.path`, not `process.cwd()`.

With current implementation, when `assetPath` is `../dist/index.html` and `output.path` is `/Users/gajus/Documents/dev/applaudience/showtime-dashboard/client/dist/static`, the copied files ends up in `/Users/gajus/Documents/dev/applaudience/showtime-dashboard/client/dist/dist/index.html`.

**Comment by gajus** [comment]
@kevlened any chance on inspecting this last issue?

**Comment by gajus** [comment]
@kevlened Please see the PR https://github.com/kevlened/copy-webpack-plugin/pull/19

**Comment by gajus** [comment]
Can you make me a contributor? I would happily with bugs as I come across them.
