### ISSUE TITLE
Absolute paths don’t work

### ISSUE THREAD

**Issue by rauschma** [kevlened/copy-webpack-plugin#2]
```js
{
    from: '/Users/rauschma/react-test/html',
    to: '/Users/rauschma/react-test/build'
}
```
These two paths lead to:

* `/Users/rauschma/react-test/html/index.html` being copied to
* `/Users/rauschma/react-test/build/Users/rauschma/react-test/build/index.html`

**Comment by rauschma** [comment]
OK, I’ve figured out what happened: `to:` is interpreted as relative to `output.path` (right?). If you omit it, `to:` **is** `output.path`. Mention that in the readme?

**Comment by kevlened** [comment]
Correct. The `to: ` path is always relative to the target build directory. You're right. I'll make it clearer in the docs.

**Comment by gajus** [comment]
What is the reason for not allowing absolute paths?

**Comment by kevlened** [comment]
It's not currently possible to determine whether the `to:` path should be relative or absolute.

This could be supported by an additional property on the pattern, like `toAbsolute: true`. I'll reopen this as a feature request.

**Comment by gajus** [comment]
If path starts with / it is an absolute path, if not it is a relative pack.

**Comment by kevlened** [comment]
Introducing that convention would be a breaking change for anyone currently using `/` in front of their `to:` paths. I'd also prefer to be more explicit where it makes sense. The absolute path use case feels like an exception to normal webpack usage.

**Comment by gajus** [comment]
Then make it a major version bump and problem solved.

**Comment by gajus** [comment]
Node has a method to confirm if path is absolute (path.isAbsolute()). No need to implement your own. If you want to support old (lt 0.12) node then consider using https://www.npmjs.com/package/path-is-absolute

**Comment by kevlened** [comment]
@gajus Thanks! Fixed

**Comment by aush** [comment]
@kevlened 
Doesn't work for me. I'm on windows. 1.1.1.

**Comment by JoshZA** [comment]
@kevlened Doesn't work on windows

**Comment by sgentile** [comment]
Doesn't work on OSX   I have

```
new CopyWebpackPlugin([
            {from: PATHS.src + '/assets/**/*.json', to: PATHS.src}
        ])
```
it should be copying all the files from the assets folder to the root of src folder, but instead it's copying all the files into src/assets

**Comment by sgentile** [comment]
I should also add that even trying to do this isn't working as workaround:

```
{from: PATHS.src + '/assets/**/*.json', to: '../../'}
```
