### ISSUE TITLE
copy dot files

### ISSUE THREAD

**Issue by alex88** [kevlened/copy-webpack-plugin#22]
I've this config:

```
new CopyWebpackPlugin([
        { from: `${paths.static}/pom.xml` },
        { from: `${paths.static}/.htaccess` }
      ], {
        ignore: []
      }),
```

however the file .htaccess isn't copied, what could be?

**Comment by alex88** [comment]
Nvm, stupid mistake

**Comment by jayrmotta** [comment]
@alex88 I'm probably making the same stupid mistake, can you tell what you found about it please?

**Comment by alex88** [comment]
@jayrmotta I don't remember actually, I don't have that code in any repo either, maybe the ignore key is wrong, I really don't know sorry

**Comment by SenHeng** [comment]
In case @jayrmotta or anyone else is still facing this problem, this is how I solved it. By adding a `./` in front of the `to:` path. Before that, it either put it in a .htaccess (`root/.htaccess/.htaccess`) directory, or didn't do anything at all.

`{ from: 'app/.htaccess', to: './.htaccess'}`

**Comment by DanieldeJong93** [comment]
For people looking in the future, i was checking the directory with 'ls' instead of 'ls -a', so the file was actually being copied

`new CopyWebpackPlugin([
      {from: './public/.htaccess'}
    ])`
