### ISSUE TITLE
Absolute paths don't work on Windows

### ISSUE THREAD

**Issue by JoshZA** [kevlened/copy-webpack-plugin#26]
On 1.1.1 

Config:
```
    new CopyWebpackPlugin([
        {from: 'src/assets/*.*', to: path.resolve(__dirname, '../dist')}
    ])
```

I had to revert to 1.0.0 to get this working

The path resolves to ```C:\node\sp_app\dist```

**Comment by forfuns** [comment]
some on OSX

**Comment by facboy** [comment]
don't seem to work on Linux either.

**Comment by SteveALee** [comment]
had same problem on windows. had to use To = relative and set output path

**Comment by ccbikai** [comment]
index.js line 51 `relDest = path.relative(baseDir, relDest);`  =>  `relDest = path.relative(relDest, baseDir);`

it works

**Comment by kevlened** [comment]
Absolute `to` paths were broken, but this should work in v2.0.1 now
