### ISSUE TITLE
Support for alias

### ISSUE THREAD

**Issue by pavankumarkatakam** [kevlened/copy-webpack-plugin#34]
in webpack config there is alias thing which im using when requiring the files. 

```
 resolve: {
        modulesDirectories: [node, bower],
        alias: {
            'node': node,
            'bower': './bower-components'
        }
    },
```

and using that as `require('bower/jquery/dist/jquery.min.js')` . I want this to support for this plugin also.

**Comment by kevlened** [comment]
I'm not sure I understand your request. What's an example of how you'd like to use the plugin with aliases?

**Comment by landed1** [comment]
I would love to know what alias is used for in webpack.

**Comment by pavankumarkatakam** [comment]
See this is one of my webpack config .. . .. . 

```
  resolve: {
        modulesDirectories: [node, bower],
        alias: {
            'node': node,
            'bower': bower,
            'jquery': "bower/jquery/dist/jquery.js",
            'moment': "bower/moment/moment.js",
            'source': source,
            'framework': framework,
            'common': common,
            'support': support,
            'application': application,
            'distribution': development,
            "environment": "../environment/dev.js"
        }
    },

```

By this config, i use the support and common folder when ever i require the files in that folder regarding the where the file is it will automatically resolve.

**Comment by aj0strow** [comment]
@pavankumarkatakam it sounds like want to require local modules easily. Use [webpack `resolve.root`](https://webpack.github.io/docs/configuration.html#resolve-root) to for local imports. 

Example:

```js
// webpack.config.js

  resolve: {
    root: [
      path.resolve(__dirname, "common"),
      path.resolve(__dirname, "support"),
   ]
  }
```

Then if you have a module `$project/common/myModule` you can import it without prefix.

```js
import "myModule"
```

None of this relates to copying static files however, which is what `copy-webpack-plugin` does.

**Comment by kevlened** [comment]
Thanks @aj0strow
