### ISSUE TITLE
ERROR in undefined is not a function

### ISSUE THREAD

**Issue by Auha** [kevlened/copy-webpack-plugin#36]
I am trying to copy an assets folder to my `build` directory. When I am running any type of webpack build commands I get an `ERROR in undefined is not a function`. It is working the way I am expecting it, but it does give me that message. I am one of those people that don't like error messages, so I was wondering if there was something I am not seeing here. I have all of the basic requirements to do the copy. Here is a rough look at my config file:

```javascript
var info = require('./package.json');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var path = require('path');
var CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    
    entry: {
        'polyfills': 'angular2/bundles/angular2-polyfills',
        'vendor': './src/vendor.ts',
        'app': './src/bootstrap.ts'
    },
    output: {
        path: path.join(__dirname, 'build/'),
        filename: 'bundle-' + info.name + '-[name]-' + info.version + '.js' 
        
    },
    devServer: {
        outputPath: path.join(__dirname, 'build')
        
    },
    context: path.join(__dirname),
    devtool: 'inline-source-map',
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js', 
        '.tpl.html'],
        root: path.resolve('.src'),
        moduleDirectories: ['node_modules', 'src', 'typings']

    },
    module: {
        loaders: [
            {
                test: /\.ts(x?)$/,
                loader:'ts-loader',
                exclude: /node_modules/
            }
        ]
        
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'src/index.html'
        }),
        new CopyWebpackPlugin([
            {
                from: 'src/assets',
                to: 'assets'
                
            }
        ])
    ]
};
```

I hope its just a stupid configuration issue, but I am lost at the moment.

**Comment by kevlened** [comment]
I don't see anything wrong with the config (at least for the copy-webpack-plugin side). Do you have a stacktrace for that error?

**Comment by bergr01** [comment]
How does one even get a stack trace from webpack? I've got a similar useless message when I try to build my project at the moment...

**Comment by bergr01** [comment]
After doing some more local debugging looks like this error is due to 

var union = function union(set1, set2) {
    return new Set([].concat(_toConsumableArray(set1), _toConsumableArray(set2)));
};

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }
(or, to be more specific, the Array.from(...))

being invoked with new Set() and causing [TypeError: undefined is not a function]
Looks like something babel-related... similar to http://stackoverflow.com/questions/32000374/es6-babel-spread-error-with-set

**Comment by bergr01** [comment]
Upgrading my Node version to 4.4.4 and rebuilding my node_modules seems to have made the issue go away, hopefully that helps someone out there!

**Comment by landed1** [comment]
I have this error here too :( but it appears to have worked..though doesn't give me full confidence.

**Comment by landed1** [comment]
I ran the node updater here and now version is 6.0.0 and no error. Thanks berg for the tip and Auha for the initial issue raise. BUT more than this thanks for a sane way (gulp spoilt brat here) to simply copy files and folders ....file-loader - pah !

**Comment by kevlened** [comment]
@Auha does the latest version resolve your issue?

**Comment by landed1** [comment]
in my case yes.
