### ISSUE TITLE
Hardcoded path separator

### ISSUE THREAD

**Issue by rauschma** [kevlened/copy-webpack-plugin#4]
```js
if (_.first(relFileDest) === '/') {
      relFileDest = relFileDest.substr(1);
    }
```

Is the slash required by webpack? If it isn’t, I’d use [`path.sep`](https://nodejs.org/docs/latest/api/path.html#path_path_sep), so that the plugin also works on Windows. Also: `slice()` is normally a better choice than `substr()` (which is not part of main ES5).

**Comment by kevlened** [comment]
The slash isn't required by webpack. I'll fix both.
