### ISSUE TITLE
permission denied, mkdir

### ISSUE THREAD

**Issue by jseminck** [kevlened/copy-webpack-plugin#41]
After upgrading from version 1.1.1 to 2.0.0 I get the following error... no other configuration has changed.

```
Unhandled rejection Error: EACCES: permission denied, mkdir '/_karma_webpack_'
    at Error (native)
```

Is this a known issue? Do you have any idea what might be going on? I looked around but couldn't find anything. 
Downgrading back to 1.1.1 works as before, which is pretty weird given the error is related to permission denied.

**Comment by kevlened** [comment]
It looks like it's trying to create `_karma_webpack_` in your system's root directory (which would require sudo permissions). This looks like a bug, but I'll need to see your CopyWebpackPlugin config to reproduce it.

**Comment by jseminck** [comment]
Hmm. Ok. Our configuration is nothing special, just a bunch of from/to objects:

```js
`new CopyWebpackPlugin([
            {
                from: path.join(__dirname, "resources", "some_dir"),
                to: "some_dir"
            },
            ... about 10 of these
]
```

Looks like it only happens when executing tests. so there is some combination of plugins messing up somewhere. I'll dig around a bit and let you know if I figure out some more information (as I don't have anything else right now).

**Comment by jseminck** [comment]
Somehow the issue solved itself. No idea why/how. Closing this.

**Comment by nene** [comment]
Looks like the issue is still present. (I'm a team-mate of @jseminck )

The problem appeared when upgrading from copy-webpack-plugin 1.1.1 to 2.0.0 (same issue with latest 2.1.3).

Solved it by disabling the plugin for Karma (we don't really need copy-files for our unit-tests anyway).

**Comment by kd35a** [comment]
We are also experiencing this issue. We've tried `rm -rf node_modules && npm install`, but that didn't help. Downgraded to 1.1.1 until this issue is resolved.

Can this issue please be re-opened, as it seems like we are multiple people experiencing it?

**Comment by kevlened** [comment]
I never write directly to the filesystem in v3.0.0, so please try with that version.

**Comment by jseminck** [comment]
3.0.0 seems to work for us, although we already used another workaround which we will probably keep (disable plugins for our tests).

**Comment by jbender** [comment]
I'm having this issue on `v3.0.1`, so I would guess that @jseminck's problem was solved by disabling the plugin rather than the version bump

**Comment by don-bluelinegrid** [comment]
Also having same issue:

```
 95% emittingError: EACCES: permission denied, mkdir '/locales'
    at Error (native)

```

**Comment by Bruce-Jcw** [comment]
+1, anyone fix it ? "version": "3.0.1"

**Comment by Bruce-Jcw** [comment]
fix it. DO NOT add slash at front.  
{ from: path.join(__dirname, '../src/_locales'), to: '/_locales' }  ====> wrong, error permission denied
{ from: path.join(__dirname, '../src/_locales'), to: '_locales' }  ====> right

**Comment by a-pandey** [comment]
```
module.exports = {
    entry: "./main.js",
    output: {
        path: "/build",
        filename: "build.js"
    },

```

If I remove `/` from the path, webpack-dev-server throws an error,
`The provided value "build" is not an absolute path`

Any help?

**Comment by jbolotin** [comment]
Per the [webpack docs](https://webpack.github.io/docs/configuration.html#output-filename) , changing output.path to __dirname + "/your-export-directory" should resolve this

**Comment by erquhart** [comment]
Yep, this should be closed based on @jbolotin's comment, worked for me.

**Comment by hackgeeks** [comment]
yes I also faced this issue in latest version webpack, then I found that by removing the "/" from the beginning of the path`s, resolved the issue.
**firstly I have done this:**
let path = require('path'),
	HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
	entry: './index.js',
	output: {
		filename: '[name]-bundle-[hash].js',
		path: path.resolve(__dirname,'/public')
	},
	module: {
		rules:[{
			test: /\.js$/,
			exclude: /node_modules/,
			use: 'jshint-loader'
		}]
	},
	plugins: [
		new HtmlWebpackPlugin({
      		template: "/public/index.html"
    	})
	]
}

**Then by removing "/"**
let path = require('path'),
	HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
	entry: './index.js',
	output: {
		filename: '[name]-bundle-[hash].js',
		path: path.resolve(__dirname,'public')
	},
	module: {
		rules:[{
			test: /\.js$/,
			exclude: /node_modules/,
			use: 'jshint-loader'
		}]
	},
	plugins: [
		new HtmlWebpackPlugin({
      		template: "public/index.html"
    	})
	]
}

**Comment by evilebottnawi** [comment]
@jseminck please create separetly issue and use ````js` for code, Thanks!

**Comment by jseminck** [comment]
I think you tagged the wrong person 😄

**Comment by evilebottnawi** [comment]
@jseminck oh sorry :smile:

**Comment by evilebottnawi** [comment]
@hackgeeks ping please see above posts

**Comment by timurcatakli** [comment]
This worked for me:
```
      new CopyWebpackPlugin(
        [
          {
            context: './src/',
            from: '**/*.html',
            to: './',
            force: true,
          },
        ],
        {
          copyUnmodified: true,
        },
      ),
```

**Comment by HouCoder** [comment]
For me, this issue was caused by a wrong `publicPath` setting, before it was

```js
output: {
    filename: '[name]/app.[hash].js',
    path: path.join(__dirname + '/dist'),
    publicPath: 'http://127.0.0.1:8089',
},
```

It works after changing `http://127.0.0.1:8089` to `http://127.0.0.1:8089/`.
