### ISSUE TITLE
devServer.outputPath must be defined in the webpack config

### ISSUE THREAD

**Issue by amgohan** [kevlened/copy-webpack-plugin#44]
copy-webpack-plugin fails when configuring webpack as :  

```
output: {
    path:       path.join(__dirname, 'build'),
    publicPath: '/',
    filename:   'js/app.js'
  }
```

instead of : 
```
devServer: {
      outputPath: path.join(__dirname, 'build')
}
```

**Comment by kevlened** [comment]
Right now, it's necessary to have both defined if you're using the devServer. When webpack uses the devServer, the `output.path` value is empty, so I have to use `devServer.outputPath`. This is a known issue: https://github.com/webpack/webpack-dev-server/issues/337

**Comment by steven-haddix** [comment]
@kevlened It looks like this option is now removed in Webpack 2. Is this option still needed?
