### ISSUE TITLE
Problems while using ignore : ERROR in Cannot read property 'glob' of undefined

### ISSUE THREAD

**Issue by landed1** [kevlened/copy-webpack-plugin#45]
plugins: [
    new CopyWebpackPlugin([
      {ignore: [
                '/app',
              ]},
      { from: path.resolve(__dirname, 'src'), to: path.resolve(__dirname, 'build') }
    ])
  ]

**Comment by kevlened** [comment]
I reverted the changes made yesterday. 2.1.5 may resolve this

**Comment by kevlened** [comment]
Sorry, 2.1.5 won't fix your issue, because the config is incorrect. Try this:

    plugins: [
        new CopyWebpackPlugin([{
            from: path.resolve(__dirname, 'src'),
            to: path.resolve(__dirname, 'build')
        }],
        {
            ignore: [
                '/app',
            ]
        })
    ]

**Comment by landed1** [comment]
I'm sorry this is the same config as far as I can see.

**Comment by kevlened** [comment]
I imagine you intend to ignore everything in that directory, so you probably want it to be `/app/**/*` and you probably want to ignore files that start with a `.` too.

    plugins: [
        new CopyWebpackPlugin([{
            from: path.resolve(__dirname, 'src'),
            to: path.resolve(__dirname, 'build')
        }],
        {
            ignore: [{
                glob: '/app/**/*',
                dot: true
            }]
        })
    ]

**Comment by landed1** [comment]
Thanks this is now working for me :)
