### ISSUE TITLE
2.1.4 broke something

### ISSUE THREAD

**Issue by jmbarbier** [kevlened/copy-webpack-plugin#46]
Using AngularClass/angular2-webpack-starter with 2.1.4 (with node 5.10.1) raises an error 
    
    new CopyWebpackPlugin([{from: 'src/assets', to: 'assets'}]),
    TypeError: CopyWebpackPlugin is not a function

reverting to 2.1.3 is OK. Something changed in your build process that makes the package fails with my setup. I'm on hurry, so i cannot investigate more for now, sorry.

**Comment by jantimon** [comment]
Same here

**Comment by kevlened** [comment]
Reverting the changes. Will investigate this weekend

**Comment by kevlened** [comment]
2.1.5 has been published

**Comment by jmbarbier** [comment]
2.1.5 and 2.1.6 are OK, closing this and related
