### ISSUE TITLE
Error: CopyWebpackPlugin is not a function

### ISSUE THREAD

**Issue by schirrmacher** [kevlened/copy-webpack-plugin#47]
I'm getting the following error when using Version 2.1.4:
> module.exports = new CopyWebpackPlugin([{
>                  ^
> 
> TypeError: CopyWebpackPlugin is not a function
>     at Object.<anonymous> (build/copy.js:3:18)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (build/webpack.config.js:32:5)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at module.exports 

2.1.3 runs without problems.

**Comment by IGZangelsanchez** [comment]
2.1.4 is broken :(

**Comment by lamo2k123** [comment]
use CopyWebpackPlugin.default

**Comment by t0rrro** [comment]
using CopyWebpackPlugin.default resolved this for me.

**Comment by kevlened** [comment]
I'm reverting the changes and pushing a new version, so this shouldn't be necessary. I'll investigate further this weekend

**Comment by kevlened** [comment]
Installing 2.1.5 should resolve this

**Comment by Luchillo** [comment]
@kevlened It does, however my error was about the plugin not being a constructor?

**Comment by kevlened** [comment]
I understand. I don't have time to investigate right now, so instead of blocking people on this issue, I pushed a fixed version.

**Comment by Luchillo** [comment]
It's ok, actually people only needed to revert to previous version instead of you pushing a revert but i guess that works too.

**Comment by kevlened** [comment]
2.1.6 is now published and should fix the issue

**Comment by lakshya-8** [comment]
I'm getting the same error after installing `"copy-webpack-plugin": "^4.6.0",`.

**Comment by kievmontana** [comment]
Hey! 
this might help
https://github.com/webpack-contrib/copy-webpack-plugin/issues/184
