### ISSUE TITLE
Ignore files?

### ISSUE THREAD

**Issue by rauschma** [kevlened/copy-webpack-plugin#5]
It’d be nice if one could specify files to ignore via globs (think `.gitignore`). Library for globs: https://github.com/isaacs/minimatch

**Comment by kevlened** [comment]
Good idea

**Comment by rauschma** [comment]
(Couldn’t find a way to reach you, which is why I’m using this channel.)

Thanks for this plugin, I’m using it in the following project: https://github.com/rauschma/react-starter-project

**Comment by kevlened** [comment]
No problem! Thanks for reaching out.

I'm glad it works for you. Your starter project is exactly what I was
looking for earlier this morning. With the recent changes to Babel and
React, I had to piece my own boilerplate together, minus hot loading. Your
project adds hot loading and looks really clean, so I'll definitely use it
to start my next project.

**Comment by rauschma** [comment]
Glad it’s useful!
