### ISSUE TITLE
is there a debug mod?

### ISSUE THREAD

**Issue by amgohan** [kevlened/copy-webpack-plugin#50]
is there a debug mode to be able to see what files are copied.
because I added the right configuration but nothing copied and my service started without any problem. But I have missing files in my public folder.

**Comment by kevlened** [comment]
There's not currently a debug mode for this plugin. If you're running a dev server, webpack doesn't write any files to the filesystem. All the files will be [stored in memory](https://webpack.github.io/docs/webpack-dev-server.html#content-base).

> This modified bundle is served from memory at the relative path specified in publicPath (see API). It will not be written to your configured output directory.

**Comment by boxxxie** [comment]
i think i'm having a similar problem. i expect my files to be moved, but they are not moved and there is no logging to tell me if things are working or not.

when i use the plugin to move one file, with absolute path, to another absolute path, and use force/copyUnmodifed... i can't access the file from the frontend.

when i use express.use(path, express.static(path)); then i can get my static files.
not sure how i would achieve the same thing with this plugin.

**Comment by maxmumford** [comment]
I was also using this plugin to move static files into a public directory and it took me a good half hour to discover this "in memory" functionality as the actual cause. 

+1 for an info message in the console, and ideally a switch to disable this functionality, as (for me at least) it's not useful in a dev environment.

**Comment by kevlened** [comment]
v4.0.0 includes a debug mode with 3 levels of debugging: `warning`, `info` and `debug`

@maxmumford @boxxxie If you're using webpack-dev-server, the plugin should work with absolute file paths now. If you're using an older version of webpack-dev-server, you may need to define `devServer.outputPath`. An error is thrown if that's necessary, otherwise, it should work.

**Comment by fairking** [comment]
> @kevlened  v4.0.0 includes a debug mode with 3 levels of debugging: warning, info and debug

Cannot find it in the [docs](https://webpack.js.org/plugins/copy-webpack-plugin/).

Can someone please explain how do I enable the debug mode??

Would be nice to put it into the docs too.
