### ISSUE TITLE
Doesn't Work Node 6.1

### ISSUE THREAD

**Issue by alexprice91** [kevlened/copy-webpack-plugin#52]
It doesn't appear to be working for Node 6.1. I am getting this error:

`ERROR in EISDIR: illegal operation on a directory, read`

**Comment by luisherranz** [comment]
I see the same error but my node is v4.3.1.

**Comment by luisherranz** [comment]
In my case the problem was with the glob.

**Comment by Naquaduh** [comment]
I have the same issue and am using a glob like so.
`from: { glob: '**/*' }`

What did you do to fix it?

**Comment by smajl** [comment]
Same problem here on 6.2.0. The error basically means that it tries to read something as a file, but it is actually a directory. It fails, when your glob patterns contains subdirectories. It works when reading a directory without subdirectories.

Definitely needs fixing.

**Comment by kevlened** [comment]
This should be resolved in 3.0.1. Thanks for reporting!
