### ISSUE TITLE
ignore is not working

### ISSUE THREAD

**Issue by aanavaneeth** [kevlened/copy-webpack-plugin#54]
I am trying to move all files from my current folder to dist folder. `node_modules` is also present in current folder. I was trying to ignore `node_modules` folder whiile copying. I have used the following snippet:
`new CopyWebpackPlugin( [  {  from: '.'  } ], { ignore: [ 'node_modules' ] } )`

And this is not at all working

**Comment by aanavaneeth** [comment]
Got the issue. My configuration was wrong. the correct configuration is:
`new CopyWebpackPlugin( [ { from: '.' } ], { ignore: [ 'node_modules/*' ] } )`

Please close the issue!

**Comment by aanavaneeth** [comment]
it worked but, it is keeping  folders. it is avoiding only files. Is there a way to avoid everything include the `node_modules` folder itself?

**Comment by kevlened** [comment]
So, you're almost there. To get it to work today, try:
`new CopyWebpackPlugin( [ { from: '.' } ], { ignore: [ 'node_modules/**/*' ] } )`

I guess it could be made a bit cleaner. Most of the time, if someone passes something that looks like a directory, they want to exclude everything in that directory, so in the future, you could use something like this:
`new CopyWebpackPlugin( [ { from: '.' } ], { ignore: [ 'node_modules' ] } )`

**Comment by aanavaneeth** [comment]
@kevlened nope. This is still keeping folders :( 
I dont want the 'node_modules' folder at all...

**Comment by kevlened** [comment]
Make sure to clean your build directory. Webpack doesn't clean it before copying things to it, so you may see old folders. Another possibility is some of the folders have files that start with dots. We'll ignore those too:

    new CopyWebpackPlugin([{ from: '.' }], {
        ignore: [{
            dots: true,
            glob: 'node_modules/**/*'
        }]
    })

I should make this easier, or add it to the docs as an example

**Comment by aanavaneeth** [comment]
Hurray It worked! but a minor correction! it should be `dot: true` not `dots: true`

But, lets have the enhancement! that helps! :)

**Comment by kevlened** [comment]
This is now the default in v4.0.0. Thanks for filing the issue!

**Comment by aanavaneeth** [comment]
That's great, @kevlened  :)

**Comment by panchalkalpesh** [comment]
@kevlened You saved us a lot of trouble. Thanks!

**Comment by xgqfrms** [comment]
# ignore  bug

> not ignore folders

![image](https://user-images.githubusercontent.com/7291672/41018812-500943fe-698e-11e8-9529-b42e87f88032.png)

![image](https://user-images.githubusercontent.com/7291672/41018832-6f770366-698e-11e8-9254-11d0ccc55b4d.png)


***

# copy-webpack-plugin ignore folder

https://github.com/webpack-contrib/copy-webpack-plugin/issues/54

# OK

>  ignore `folder` & `any thing in the folder` === `"libs/**/*"`

> ignore some `.extension` files === `["*.md", "*.js", "*.css" ]`

```js
// ignore folder & any thing in the folder === "libs/**/*"
// ignore some .extension files === ["*.md", "*.js", "*.css" ]

    new CopyWebpackPlugin([
        {
            from: "./src/backend-system/",
            to: "../",
            ignore: ["*.md", "*.js", "*.css", "others/*", "libs/**/*"]
        },
        {
            from: "./src/backend-system/index.css",
            to: "./css/"
        }
    ]),
```

**Comment by miked1ck** [comment]
@xgqfrms – thank you! `"libs/**/*"` to ignore folder AND its contents

**Comment by xgqfrms** [comment]
@miked1ck  You are welcome!

**Comment by Reema4692** [comment]
> # ignore bug
> > not ignore folders
> 
> ![image](https://user-images.githubusercontent.com/7291672/41018812-500943fe-698e-11e8-9529-b42e87f88032.png)
> 
> ![image](https://user-images.githubusercontent.com/7291672/41018832-6f770366-698e-11e8-9254-11d0ccc55b4d.png)
> 
> # copy-webpack-plugin ignore folder
> #54
> 
> # OK
> > ignore `folder` & `any thing in the folder` === `"libs/**/*"`
> 
> > ignore some `.extension` files === `["*.md", "*.js", "*.css" ]`
> 
> ```js
> // ignore folder & any thing in the folder === "libs/**/*"
> // ignore some .extension files === ["*.md", "*.js", "*.css" ]
> 
>     new CopyWebpackPlugin([
>         {
>             from: "./src/backend-system/",
>             to: "../",
>             ignore: ["*.md", "*.js", "*.css", "others/*", "libs/**/*"]
>         },
>         {
>             from: "./src/backend-system/index.css",
>             to: "./css/"
>         }
>     ]),
> ```
> 
> ![image](https://user-images.githubusercontent.com/7291672/41019067-a25aec06-698f-11e8-971d-ad1551d409b2.png)
> 
> ![image](https://user-images.githubusercontent.com/7291672/41019205-46f13536-6990-11e8-904d-5a97b64f0f16.png)

Worked for me.. Thanks.. :)
