### ISSUE TITLE
not working, no error, no files were copy

### ISSUE THREAD

**Issue by craigcosmo** [kevlened/copy-webpack-plugin#56]
my folder structure
```
project
  |app
  |image
```

my config

```
module.exports = {
	context: __dirname + "/app",
	entry:[
		"./index.js"
	],
	output: {
		path: __dirname + '/public',
		filename: "bundle.js",
		publicPath: "/public/"
	},
	plugins: [
		new CopyWebpackPlugin([{from: 'image'}])
	]
}
```

**Comment by aanavaneeth** [comment]
hi probably because of your context. your context is `app` but `image` folder is there in `project` folder

**Comment by AlexKvazos** [comment]
Having the same issue #57

**Comment by craigcosmo** [comment]
@aanavaneeth  you are right. I remove the context app, it works now.

**Comment by kevlened** [comment]
Thanks @aanavaneeth!

**Comment by aanavaneeth** [comment]
I usually maintain like the below: (I am not enforcing you)

project (simple site. non-angular. for angular, better follow component based folders)
  |src
    | img
    | scss
    |JS
  |package.json
  | webpack.config.js
