### ISSUE TITLE
It doesn't work with webpack-dev-server

### ISSUE THREAD

**Issue by AlexKvazos** [kevlened/copy-webpack-plugin#57]
I have nearly the same config for building and for watching, but when using watch, no output folder gets created and no error is shown in the console.

```
new CopyWebpackPlugin([{ from: path.join(__dirname, '../resources')}], { copyUnmodified: true }),
```

```
devServer: {
    hot: true,
    port: 8080,
    host: '0.0.0.0',
    inline: true,
    contentBase: path.join(__dirname, '../www'),
    outputPath: path.join(__dirname, '../www'),
    publicPath: '/',
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  }
```

**Comment by AlexKvazos** [comment]
So I just checked that 3.0.0 removes writing to the FS, but doesn't that mean that the files should be available from memory?

**Comment by AlexKvazos** [comment]
Sorry ._.

**Comment by kevlened** [comment]
No worries! The files (as well as your bundle) are available from memory on the dev-server. This is true for all dev-server assets. If you really want to write the assets to the filesystem when running a dev-server, use the [write-file-webpack-plugin](https://github.com/gajus/write-file-webpack-plugin).

[Reference](https://webpack.github.io/docs/webpack-dev-server.html#content-base)

> Using this config webpack-dev-server will serve the static files in your build folder. It’ll watch your source files for changes and when changes are made the bundle will be recompiled. **This modified bundle is served from memory at the relative path specified in publicPath (see API)**. It will not be written to your configured output directory.
