### ISSUE TITLE
Plugin should fail when file not found

### ISSUE THREAD

**Issue by aj0strow** [kevlened/copy-webpack-plugin#66]
Would you accept a PR to fail the build when the `from` file or directory is not found? 

Here's what happened this morning. Netlify allows static routing, but I need to copy `_redirects` into the output folder. 

```js
  new CopyWebpackPlugin([
    {
      from: path.join(__dirname, "/src/_redirects"),
      to: "_redirects",
      toType: "file"
    },
  ]),
```

Let's say someone (me, last night) changes the `from` field to:

```
from: path.resolve(__dirname, "/src/_redirects")
```

Now the file is not found (it's an absolute path) and is not copied to the output folder. Every page on the website besides the root path 404's. That shouldn't happen, the build should have failed instead.

**Comment by foxbunny** [comment]
Or at least emit a warning. I got caught by this as well, and was scratching my head for quite a while.

**Comment by kevlened** [comment]
v4.0.0 now emits a warning on missing source files (or directories). If you'd like this to fail the build, also include [NoErrorsPlugin](https://github.com/webpack/docs/wiki/list-of-plugins#noerrorsplugin).

**Comment by aj0strow** [comment]
@kevlened thanks, upgrading!
