### ISSUE TITLE
Preserve file permissions

### ISSUE THREAD

**Issue by guatedude2** [kevlened/copy-webpack-plugin#68]
Looks like copy-webpack-plugin isn't preserving the permissions of the source, I'm copying "electron-prebuilt/dist/Electron.app" folder to "build/My App.app". Looks like all files get copied but the app doesn't work because the "Electron.app/Contents/MacOS/Electron" file doesn't have the right permissions.

I'm using this as part of the release process not for development

**Comment by kevlened** [comment]
Merging this into #35

**Comment by jessica-pixvana** [comment]
I'm also trying to preserve the file permissions during a copy. Whats the status of this?

**Comment by andresmatasuarez** [comment]
anyone here? 2021 and it's still not working
