### ISSUE TITLE
Why make the destination relative?

### ISSUE THREAD

**Issue by refaelos** [kevlened/copy-webpack-plugin#72]
If the source is absolute path you're making the dest path relative... why?

```
...
// If the pattern is a blob
                        if (!stat) {
                            // If the source is absolute
                            if (_path2.default.isAbsolute(relFileSrc)) {
                                // Make the destination relative
                                relFileDest = _path2.default.join(_path2.default.relative(context, relFileDirname), _path2.default.basename(relFileSrc));

                                // If the source is relative
                            } else {
                                    relFileDest = _path2.default.join(relFileDest, relFileSrc);
                                }

                            // If it looks like a directory
                        } else if ((0, _toLooksLikeDirec...
```

When I put a source and destination path absolute I want them to stay absolute ... right?

This is my code:
`new CopyWebpackPlugin([{from: path.join(__dirname, root, 'assets/**/*'), to: path.join(__dirname, 'public/assets')}])`

**Comment by kevlened** [comment]
We don't write files directly to the filesystem (using `fs`). Instead, we write files to `compilation.assets` (webpack's asset management), then webpack writes the results. The keys in `compilation.assets` are file paths that are relative to the output directory, so we have to convert absolute paths to relative ones.

If you're having trouble figuring out where the plugin is writing your files, the latest version (v4.0.0) has a debug mode. Set it to `info` to see where it's writing your files.
