### ISSUE TITLE
Glob copy broken for single files/folder

### ISSUE THREAD

**Issue by filipesilva** [kevlened/copy-webpack-plugin#73]
Having `src/assets/file.txt`:
- `{ context: 'src/', from: { glob: 'assets/*.txt' }}` copies to `dist/assets/file.txt`
- `{ context: 'src/', from: { glob: 'assets/file.txt' }}` copies to `dist/file.txt` (no `assets/` dir)

Having specified `from` with `glob`, I would expect both patterns to behave similarly since both are valid globs that return the same file when used with `glob`:

```
var glob = require("glob")
glob("src/assets/*.txt", (err, files) => console.log(files)); // [ 'src/assets/file.txt' ]
glob("src/assets/file.txt", (err, files) => console.log(files)); // [ 'src/assets/file.txt' ]
```

**Comment by kevlened** [comment]
We treat globs different than file or directory paths. With file or directory paths, we can automatically figure out a context, where a glob is more difficult.

I could make them function the same way, but it'd be kind of a hack (figuring out the context based on the first wildcard in the glob).

**Comment by filipesilva** [comment]
In my case, we just needed it to work exactly like a glob. We ended up writing a simpler plugin that just copied globs as is (https://github.com/angular/angular-cli/blob/master/packages/angular-cli/plugins/glob-copy-webpack-plugin.ts).

I understand this issue might be out of scope for `copy-webpack-plugin`.

**Comment by kevlened** [comment]
I'm not closing this, because it's a compelling usability story. It'd be a breaking change, and involve some magic, so I'm going to push investigating this until the next major release.

**Comment by filipesilva** [comment]
It could be hidden behind a flag, e.g. `strictGlob`.

**Comment by filipesilva** [comment]
Heya, just wanted to mention that this seems to be fixed in the latest versions. Cheers!
