### ISSUE TITLE
Can't install with npm

### ISSUE THREAD

**Issue by kopax** [kevlened/copy-webpack-plugin#75]
$ npm version
     { 'react-boilerplate': '3.2.1',
       npm: '3.10.9',
       ares: '1.10.1-DEV',
       http_parser: '2.7.0',
       icu: '57.1',
       modules: '48',
       node: '6.5.0',
       openssl: '1.0.2h',
       uv: '1.9.1',
       v8: '5.1.281.81',
       zlib: '1.2.8' }
    $ npm --version
    3.10.9
    $ node --version
    v6.5.0

I am trying to add this project as dev dependencies : 

	 $ npm install --save-dev copy-webpack-plugin
	react-boilerplate@3.2.1 /workspace/github.com/mxstbr/react-boilerplate
	├── UNMET PEER DEPENDENCY cheerio@0.22.0
	└── copy-webpack-plugin@3.0.1 

	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
	npm WARN chai-enzyme@0.5.1 requires a peer of cheerio@0.19.x || 0.20.x but none was installed.
	npm WARN react-addons-test-utils@15.3.2 requires a peer of react@^15.3.2 but none was installed.

For information, this is the content of `/workspace/github.com/mxstbr/react-boilerplate/node_modules/cheerio/package.json` file so I guess it should not be a problem : 

    {
      "_args": [
        [
          {
            "raw": "cheerio@^0.22.0",
            "scope": null,
            "escapedName": "cheerio",
            "name": "cheerio",
            "rawSpec": "^0.22.0",
            "spec": ">=0.22.0 <0.23.0",
            "type": "range"
          },
          "/workspace/github.com/mxstbr/react-boilerplate"
        ]
      ],
      "_from": "cheerio@>=0.22.0 <0.23.0",
      "_id": "cheerio@0.22.0",
      "_inCache": true,
      "_location": "/cheerio",
      "_nodeVersion": "6.2.2",
      "_npmOperationalInternal": {
        "host": "packages-12-west.internal.npmjs.com",
        "tmp": "tmp/cheerio-0.22.0.tgz_1471954900169_0.12557715992443264"
      },
      "_npmUser": {
        "name": "mattmueller",
        "email": "mattmuelle@gmail.com"
      },
      "_npmVersion": "3.10.6",
      "_phantomChildren": {},
      "_requested": {
        "raw": "cheerio@^0.22.0",
        "scope": null,
        "escapedName": "cheerio",
        "name": "cheerio",
        "rawSpec": "^0.22.0",
        "spec": ">=0.22.0 <0.23.0",
        "type": "range"
      },
      "_requiredBy": [
        "#DEV:/",
        "#USER"
      ],
      "_resolved": "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz",
      "_shasum": "a9baa860a3f9b595a6b81b1a86873121ed3a269e",
      "_shrinkwrap": null,
      "_spec": "cheerio@^0.22.0",
      "_where": "/workspace/github.com/mxstbr/react-boilerplate",
      "author": {
        "name": "Matt Mueller",
        "email": "mattmuelle@gmail.com",
        "url": "mat.io"
      },
      "bugs": {
        "url": "https://github.com/cheeriojs/cheerio/issues"
      },
      "dependencies": {
        "css-select": "~1.2.0",
        "dom-serializer": "~0.1.0",
        "entities": "~1.1.1",
        "htmlparser2": "^3.9.1",
        "lodash.assignin": "^4.0.9",
        "lodash.bind": "^4.1.4",
        "lodash.defaults": "^4.0.1",
        "lodash.filter": "^4.4.0",
        "lodash.flatten": "^4.2.0",
        "lodash.foreach": "^4.3.0",
        "lodash.map": "^4.4.0",
        "lodash.merge": "^4.4.0",
        "lodash.pick": "^4.2.1",
        "lodash.reduce": "^4.4.0",
        "lodash.reject": "^4.4.0",
        "lodash.some": "^4.4.0"
      },
      "description": "Tiny, fast, and elegant implementation of core jQuery designed specifically for the server",
      "devDependencies": {
        "benchmark": "^2.1.0",
        "coveralls": "^2.11.9",
        "expect.js": "~0.3.1",
        "istanbul": "^0.4.3",
        "jquery": "^3.0.0",
        "jsdom": "^9.2.1",
        "jshint": "^2.9.2",
        "mocha": "^2.5.3",
        "xyz": "~0.5.0"
      },
      "directories": {},
      "dist": {
        "shasum": "a9baa860a3f9b595a6b81b1a86873121ed3a269e",
        "tarball": "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz"
      },
      "engines": {
        "node": ">= 0.6"
      },
      "files": [
        "index.js",
        "lib"
      ],
      "gitHead": "35c4917205dca9d08139c95419e2626c0689e38a",
      "homepage": "https://github.com/cheeriojs/cheerio#readme",
      "keywords": [
        "htmlparser",
        "jquery",
        "selector",
        "scraper",
        "parser",
        "html"
      ],
      "license": "MIT",
      "main": "./index.js",
      "maintainers": [
        {
          "name": "mattmueller",
          "email": "mattmuelle@gmail.com"
        },
        {
          "name": "davidchambers",
          "email": "dc@davidchambers.me"
        },
        {
          "name": "jugglinmike",
          "email": "mike@mikepennisi.com"
        },
        {
          "name": "feedic",
          "email": "me@feedic.com"
        }
      ],
      "name": "cheerio",
      "optionalDependencies": {},
      "readme": "ERROR: No README data found!",
      "repository": {
        "type": "git",
        "url": "git://github.com/cheeriojs/cheerio.git"
      },
      "scripts": {
        "test": "make test"
      },
      "version": "0.22.0"
    }

Is there a way to solve this ?

**Comment by schnittstabil** [comment]
Maybe:
```diff
-npm install --save-dev copy-webpack
+npm install --save-dev copy-webpack-plugin
```

**Comment by kopax** [comment]
@schnittstabil : Sorry it was my terminal that destroy the formatting. 

I confirm the command is the same as `npm install --save-dev copy-webpack-plugin` and I have edited the original question.

**Comment by schnittstabil** [comment]
@kopax Aww, I should read more carefully, I've also updated my answer.
AFAIK, `cheerio` has had some installing issues the other day.
Maybe you should remove `copy-webpack-plugin` in your `package.json` and try:
```
rm -r node_modules/
npm install
npm install --save-dev copy-webpack-plugin
```

**Comment by kopax** [comment]
The plugin is now installed, but the error remain. I will just ignore it. Thanks @schnittstabil !
