### ISSUE TITLE
Unable to ignore directory completely

### ISSUE THREAD

**Issue by jakub2** [kevlened/copy-webpack-plugin#79]
Hi, I have a directory in src/assets/css, and I want this directory to be excluded from copying. My code below excludes all files from that directory, but I want to ignore the whole directory. I don't want to have an empty directory in the destination. How can I do that please?

Here's my code from config\webpack.common.js:
```
new CopyWebpackPlugin([{
        from: 'src/assets',
        to: 'assets',
      }, {
        from: 'src/meta',
      }, ], {
        ignore: [
          'css/**/*.*'
        ]
      }),
```

**Comment by kevlened** [comment]
I'm guessing there are dot files left in the directories. See #54 for details. v4.0.0 has more reasonable defaults, so an update will probably fix your issue.
