### ISSUE TITLE
No option to match dots

### ISSUE THREAD

**Issue by JoshZA** [kevlened/copy-webpack-plugin#8]
Minimatch's options param is not exposed, so right now copy-webpack can't ignore files like '.eslint' using a pattern like '***/**'

```
function shouldIgnore(pathName, ignoreList) {
  var matched = _.find(ignoreList, function(glob) {
    return minimatch(pathName, glob, {
      matchBase: true,
      dot: true
    });
  });
```

**Comment by TeffenEllis** [comment]
@kevlened,

Could you expose this option? I'd like to include files prefixed with a dot.

Thank you!
