### ISSUE TITLE
ERROR in Path must be a string.

### ISSUE THREAD

**Issue by monolithed** [kevlened/copy-webpack-plugin#87]
```
new CopyWebpackPlugin([
	{
		from: {
			glob: 'manifest.json'
		}
	}
]);
```

```
ERROR in Path must be a string. Received { glob: 'manifest.json' }
```

```
"webpack": "^1.13.2",
"copy-webpack-plugin": "^4.0.0"
```

**Comment by didymu5** [comment]
any resolve with this? I got the same error with the same version

**Comment by kevlened** [comment]
It's not resolved yet. Looks like there's a gap in our test coverage.

**Comment by daniloprates** [comment]
Any workaround for this bug?

**Comment by monolithed** [comment]
It seems has been [fixed](https://github.com/kevlened/copy-webpack-plugin/commit/7c2e14657c1e7f8c7d8d61c77ff35b05a3c29ede) already

**Comment by choosenvictim** [comment]
I faced the same issue. Upgrading to v4.0.1 fixed it. Thanks
