### ISSUE TITLE
unable to install 4.0.1

### ISSUE THREAD

**Issue by choongmanee** [kevlened/copy-webpack-plugin#97]
Hi guys,

I was able to install 4.0.0 but had some errors with 4.0.1. The error message is below. Looks like is-glob is out of range in 4.0.1 under "dependencies":
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: is-glob@'>=3.1.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.2.0","0.3.0","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3","2.0.0","2.0.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'copy-webpack-plugin'
npm ERR! notarget 

=====
{...
  version: '4.0.1',
  main: 'dist/index.js',
  dependencies: 
   { bluebird: '^2.10.2',
     'fs-extra': '^0.26.4',
     glob: '^6.0.4',
     'is-glob': '^3.1.0',
     'loader-utils': '^0.2.15',
     lodash: '^4.3.0',
     minimatch: '^3.0.0',
     'node-dir': '^0.1.10' },
...}

**Comment by kevlened** [comment]
This is unrelated to the changes in 4.0.1. It may have been an issue with the npm registry.
